### ISSUE TITLE
Build frontend for calender view

### ISSUE THREAD

**Issue by Akinsola-M0** [zurichat/zc_plugin_duty_shift_dotnet#24]
As an employee/employer/manager, I want my Company Duty/Shift planner to have a calendar view.

**Comment by mofeforthefuture** [comment]
<img width="1280" alt="Screenshot 2021-09-01 at 13 36 34" src="https://user-images.githubusercontent.com/69436548/131672227-ed67aa84-0c6a-4863-bf68-b757839e1383.png">

**Comment by mofeforthefuture** [comment]
done

**Comment by markessien** [comment]
No testing link

**Comment by mofeforthefuture** [comment]
https://tracker.zuri.chat/

**Comment by mofeforthefuture** [comment]
this page is supposed to have a calendar and scheduled date for people
