### ISSUE TITLE
Design-Admin/Employee Schedule(mobile view)

### ISSUE THREAD

**Issue by megarchi** [zurichat/zc_plugin_duty_shift_dotnet#68]
As a user(Employee), I should be able to:
1. View my schedule
2. Filter: Daily, weekly and monthly
3. View all

As a user(Admin), I should be able to:
1. View schedule
2. Filter: Daily, weekly and monthly
3. Edit shift
4. Delete shift

Slack username: @megarchi 

mail: margaretokpani@gmail.com

Figma link:

https://www.figma.com/file/hlBzwe5KplhnkxvPtHqr0o/Team-Tolstoy-Company-Duty-Shift?node-id=0%3A1

**Comment by moh-x** [comment]
Live link: https://tracker.zuri.chat/schedule
