### ISSUE TITLE
Action to add UserType, and Get a UserType

### ISSUE THREAD

**Issue by imadonmwinyi** [zurichat/zc_plugin_duty_shift_dotnet#87]
Add Post Action and Get(id) Action to UserType Controller, that creates and return a single userType

**Comment by imadonmwinyi** [comment]
Link for testing
https://tracker.zuri.chat/api/usertypes/61321b1ab77799132acd124b

**Comment by buka4rill** [comment]
Link not working

**Comment by buka4rill** [comment]
Works now
